# I think this is redundant

workspace:
  path: "/tmp/penguin_workspace"

model:
  default: openai/gpt-5-codex
  provider: openrouter
  client_preference: openrouter
  streaming_enabled: true
  temperature: 0.3
  context_window: 272000
  max_tokens: null
api:
  base_url: null
tools:
  enabled: true
  allow_web_access: true
  allow_file_operations: true
  allow_code_execution: true
diagnostics:
  enabled: true
  verbose_logging: true

# CLI Display Settings
cli:
  display:
    style: "minimal"  # Options: minimal, compact, standard, detailed, streaming
    consolidate_system_messages: true  # Batch consecutive system messages to reduce blank lines
    hide_internal_markers: true  # Filter <execute>, <system-reminder>, etc. from output
    hide_tool_results: true  # Hide "Tool Result (execute)" system messages for clean output
    max_blank_lines: 2  # Maximum consecutive blank lines allowed in output
    deduplicate_messages: true  # Skip rendering duplicate messages
    show_timestamps: true  # Show timestamps in message headers
    show_metadata: false  # Show token counts and other metadata in message headers
