name: "Setup Git Committer"
description: "Create app token and configure git user"
inputs:
  opencode-app-id:
    description: "OpenCode GitHub App ID"
    required: true
  opencode-app-secret:
    description: "OpenCode GitHub App private key"
    required: true
outputs:
  token:
    description: "GitHub App token"
    value: ${{ steps.apptoken.outputs.token }}
  app-slug:
    description: "GitHub App slug"
    value: ${{ steps.apptoken.outputs.app-slug }}
runs:
  using: "composite"
  steps:
    - name: Create app token
      id: apptoken
      uses: actions/create-github-app-token@v2
      with:
        app-id: ${{ inputs.opencode-app-id }}
        private-key: ${{ inputs.opencode-app-secret }}
        owner: ${{ github.repository_owner }}

    - name: Configure git user
      run: |
        slug="${{ steps.apptoken.outputs.app-slug }}"
        git config --global user.name "${slug}[bot]"
        git config --global user.email "${slug}[bot]@users.noreply.github.com"
      shell: bash

    - name: Clear checkout auth
      run: |
        git config --local --unset-all http.https://github.com/.extraheader || true
      shell: bash

    - name: Configure git remote
      run: |
        git remote set-url origin https://x-access-token:${{ steps.apptoken.outputs.token }}@github.com/${{ github.repository }}
      shell: bash
