"""OpenCode-shaped command registry for Penguin TUI clients."""

from __future__ import annotations

from typing import Any


def _command(
    *,
    name: str,
    description: str,
    template: str,
    category: str,
    route: str | None = None,
    method: str = "GET",
    requires_session: bool = False,
    required_context: list[str] | None = None,
    hints: list[str] | None = None,
) -> dict[str, Any]:
    return {
        "name": name,
        "description": description,
        "template": template,
        "hints": hints if hints is not None else [],
        "source": "command",
        "category": category,
        "enabled": True,
        "requiredContext": required_context if required_context is not None else [],
        "requiresSession": requires_session,
        "execution": {
            "type": "penguin-local",
            "method": method,
            "route": route,
        },
    }


def list_opencode_commands() -> list[dict[str, Any]]:
    """Return command metadata consumed by the OpenCode-derived TUI."""
    return [
        _command(
            name="config",
            description="Show configuration sources",
            template="/config",
            category="Settings",
        ),
        _command(
            name="tool_details",
            description="Toggle tool detail visibility",
            template="/tool_details",
            category="Settings",
        ),
        _command(
            name="thinking",
            description="Toggle reasoning visibility",
            template="/thinking",
            category="Settings",
        ),
        _command(
            name="project",
            description="Create, initialize, list, show, delete, or start projects",
            template="/project $ARGUMENTS",
            category="Project",
            route="/api/v1/projects",
            method="POST",
            required_context=["workspace"],
            hints=["$ARGUMENTS"],
        ),
        _command(
            name="project-create",
            description="Create a project",
            template="/project-create $1",
            category="Project",
            route="/api/v1/projects",
            method="POST",
            required_context=["workspace"],
            hints=["$1"],
        ),
        _command(
            name="project-init",
            description="Initialize a project from a blueprint",
            template="/project-init $1",
            category="Project",
            route="/api/v1/projects/initialize",
            method="POST",
            required_context=["workspace"],
            hints=["$1"],
        ),
        _command(
            name="project-list",
            description="List projects",
            template="/project-list",
            category="Project",
            route="/api/v1/projects",
        ),
        _command(
            name="project-start",
            description="Start a project workflow",
            template="/project-start $1",
            category="Project",
            route="/api/v1/projects/{project_id}/start",
            method="POST",
            requires_session=True,
            required_context=["session", "workspace"],
            hints=["$1"],
        ),
        _command(
            name="task",
            description="Create, list, show, start, complete, execute, or delete tasks",
            template="/task $ARGUMENTS",
            category="Task",
            route="/api/v1/tasks",
            method="POST",
            required_context=["workspace"],
            hints=["$ARGUMENTS"],
        ),
        _command(
            name="task-create",
            description="Create a task under a project",
            template="/task-create $1 $2",
            category="Task",
            route="/api/v1/tasks",
            method="POST",
            required_context=["workspace"],
            hints=["$1", "$2"],
        ),
        _command(
            name="task-list",
            description="List project tasks",
            template="/task-list $1",
            category="Task",
            route="/api/v1/tasks",
            required_context=["workspace"],
            hints=["$1"],
        ),
        _command(
            name="task-show",
            description="Show task details",
            template="/task-show $1",
            category="Task",
            route="/api/v1/tasks/{task_id}",
            hints=["$1"],
        ),
        _command(
            name="task-start",
            description="Mark a task as running",
            template="/task-start $1",
            category="Task",
            route="/api/v1/tasks/{task_id}/start",
            method="POST",
            hints=["$1"],
        ),
        _command(
            name="task-complete",
            description="Mark a task as complete",
            template="/task-complete $1",
            category="Task",
            route="/api/v1/tasks/{task_id}/complete",
            method="POST",
            hints=["$1"],
        ),
        _command(
            name="task-execute",
            description="Execute a task in the current session",
            template="/task-execute $1",
            category="Task",
            route="/api/v1/tasks/{task_id}/execute",
            method="POST",
            requires_session=True,
            required_context=["session", "workspace"],
            hints=["$1"],
        ),
        _command(
            name="task-delete",
            description="Delete a task",
            template="/task-delete $1",
            category="Task",
            route="/api/v1/tasks/{task_id}",
            method="DELETE",
            hints=["$1"],
        ),
    ]
